default_language_version:
  python: python3.7

default_stages: [commit, push]

repos:
  # check yaml and end of file fixer
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE|.pickle

  # remove unused import and variable using autoflake
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [
          '--in-place',
          '--remove-all-unused-imports',
          '--ignore-init-module-imports',
          '--remove-unused-variables',
          '--'
        ]

  # sort import using isort
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: [
        '--treat-comment-as-code',
        '"# %%"',
        '--'
        ]

  # follow style using autopep8
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8

  # linting and code analysis using flake8
  # E741: ambiguous variable name
  # F403: 'from module import *' used; unable to detect undefined names
  # W503: line break before binary operator
  # W504: line break after binary operator
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [
          '--max-line-length',
          '120',
          '--ignore',
          'E402,E741,F403,W503,W504',
          '--'
        ]
